# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'US_Cal_Test.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from UI.QCustomComboBox import QCustomComboBox

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(785, 800)
        MainWindow.setMaximumSize(QtCore.QSize(785, 800))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser_note = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_note.setGeometry(QtCore.QRect(50, 30, 631, 121))
        self.textBrowser_note.setObjectName("textBrowser_note")
        self.label_savefile = QtWidgets.QLabel(self.centralwidget)
        self.label_savefile.setGeometry(QtCore.QRect(50, 160, 54, 31))
        self.label_savefile.setObjectName("label_savefile")
        self.lineEdit_savefile = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_savefile.setGeometry(QtCore.QRect(50, 190, 331, 31))
        self.lineEdit_savefile.setObjectName("lineEdit_savefile")
        self.comboBox_constellation = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_constellation.setGeometry(QtCore.QRect(50, 270, 69, 22))
        self.comboBox_constellation.setObjectName("comboBox_constellation")
        self.label_constellation = QtWidgets.QLabel(self.centralwidget)
        self.label_constellation.setGeometry(QtCore.QRect(50, 240, 81, 31))
        self.label_constellation.setObjectName("label_constellation")
        self.label_numfreq = QtWidgets.QLabel(self.centralwidget)
        self.label_numfreq.setGeometry(QtCore.QRect(160, 240, 51, 31))
        self.label_numfreq.setObjectName("label_numfreq")
        self.spinBox_numfreq = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_numfreq.setGeometry(QtCore.QRect(160, 270, 42, 22))
        self.spinBox_numfreq.setProperty("value", 0)
        self.spinBox_numfreq.setObjectName("spinBox_numfreq")
        self.spinBox_numpower = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_numpower.setGeometry(QtCore.QRect(221, 270, 51, 22))
        self.spinBox_numpower.setObjectName("spinBox_numpower")
        self.label_numpower = QtWidgets.QLabel(self.centralwidget)
        self.label_numpower.setGeometry(QtCore.QRect(220, 240, 51, 31))
        self.label_numpower.setObjectName("label_numpower")
        self.label_numpower_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_numpower_2.setGeometry(QtCore.QRect(290, 240, 71, 31))
        self.label_numpower_2.setObjectName("label_numpower_2")
        self.label_resource_name = QtWidgets.QLabel(self.centralwidget)
        self.label_resource_name.setGeometry(QtCore.QRect(440, 160, 81, 31))
        self.label_resource_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_resource_name.setObjectName("label_resource_name")
        self.comboBox_Ports = QCustomComboBox(self.centralwidget)
        self.comboBox_Ports.setGeometry(QtCore.QRect(450, 190, 69, 22))
        self.comboBox_Ports.setObjectName("comboBox_Ports")
        self.textBrowser_readedStr = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_readedStr.setGeometry(QtCore.QRect(50, 410, 231, 41))
        self.textBrowser_readedStr.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textBrowser_readedStr.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textBrowser_readedStr.setObjectName("textBrowser_readedStr")
        self.label_readstr = QtWidgets.QLabel(self.centralwidget)
        self.label_readstr.setGeometry(QtCore.QRect(50, 390, 54, 12))
        self.label_readstr.setObjectName("label_readstr")
        self.label_writestr = QtWidgets.QLabel(self.centralwidget)
        self.label_writestr.setGeometry(QtCore.QRect(50, 460, 71, 21))
        self.label_writestr.setObjectName("label_writestr")
        self.textBrowser_writeStr = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_writeStr.setGeometry(QtCore.QRect(50, 480, 621, 61))
        self.textBrowser_writeStr.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textBrowser_writeStr.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_writeStr.setObjectName("textBrowser_writeStr")
        self.label_Freqcurrent = QtWidgets.QLabel(self.centralwidget)
        self.label_Freqcurrent.setGeometry(QtCore.QRect(160, 300, 54, 21))
        self.label_Freqcurrent.setObjectName("label_Freqcurrent")
        self.textBrowser_freqCurrent = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_freqCurrent.setGeometry(QtCore.QRect(160, 320, 41, 21))
        self.textBrowser_freqCurrent.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_freqCurrent.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_freqCurrent.setObjectName("textBrowser_freqCurrent")
        self.textBrowser_powerindex = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_powerindex.setGeometry(QtCore.QRect(290, 270, 51, 21))
        self.textBrowser_powerindex.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_powerindex.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_powerindex.setObjectName("textBrowser_powerindex")
        self.label_normalCHP = QtWidgets.QLabel(self.centralwidget)
        self.label_normalCHP.setGeometry(QtCore.QRect(290, 300, 151, 21))
        self.label_normalCHP.setObjectName("label_normalCHP")
        self.textBrowse_normalCHP = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowse_normalCHP.setGeometry(QtCore.QRect(290, 320, 111, 21))
        self.textBrowse_normalCHP.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowse_normalCHP.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowse_normalCHP.setObjectName("textBrowse_normalCHP")
        self.textBrowser_measureCHP = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_measureCHP.setGeometry(QtCore.QRect(290, 370, 111, 21))
        self.textBrowser_measureCHP.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_measureCHP.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_measureCHP.setObjectName("textBrowser_measureCHP")
        self.label_measureCHP = QtWidgets.QLabel(self.centralwidget)
        self.label_measureCHP.setGeometry(QtCore.QRect(290, 350, 151, 21))
        self.label_measureCHP.setObjectName("label_measureCHP")
        self.textBrowser_response = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_response.setGeometry(QtCore.QRect(50, 570, 621, 111))
        self.textBrowser_response.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textBrowser_response.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_response.setObjectName("textBrowser_response")
        self.label_response = QtWidgets.QLabel(self.centralwidget)
        self.label_response.setGeometry(QtCore.QRect(50, 550, 71, 21))
        self.label_response.setObjectName("label_response")
        self.textBrowser_powerDiff = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_powerDiff.setGeometry(QtCore.QRect(290, 420, 111, 21))
        self.textBrowser_powerDiff.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_powerDiff.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_powerDiff.setObjectName("textBrowser_powerDiff")
        self.label_powerDiff = QtWidgets.QLabel(self.centralwidget)
        self.label_powerDiff.setGeometry(QtCore.QRect(290, 400, 151, 21))
        self.label_powerDiff.setObjectName("label_powerDiff")
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        self.label_status.setGeometry(QtCore.QRect(530, 410, 54, 12))
        self.label_status.setObjectName("label_status")
        self.textBrowser_status = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_status.setGeometry(QtCore.QRect(530, 430, 51, 21))
        self.textBrowser_status.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_status.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_status.setObjectName("textBrowser_status")
        self.label_status_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_status_2.setGeometry(QtCore.QRect(600, 410, 71, 21))
        self.label_status_2.setObjectName("label_status_2")
        self.toolButton_choosepath = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_choosepath.setGeometry(QtCore.QRect(380, 190, 37, 31))
        self.toolButton_choosepath.setObjectName("toolButton_choosepath")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 785, 23))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        self.menu_edit = QtWidgets.QMenu(self.menubar)
        self.menu_edit.setObjectName("menu_edit")
        self.menu_tool = QtWidgets.QMenu(self.menubar)
        self.menu_tool.setObjectName("menu_tool")
        self.menu_operation = QtWidgets.QMenu(self.menubar)
        self.menu_operation.setObjectName("menu_operation")
        self.menu_window = QtWidgets.QMenu(self.menubar)
        self.menu_window.setObjectName("menu_window")
        self.menu_help = QtWidgets.QMenu(self.menubar)
        self.menu_help.setObjectName("menu_help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMinimumSize(QtCore.QSize(785, 30))
        self.toolBar.setMovable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_open = QtWidgets.QAction(MainWindow)
        self.action_open.setObjectName("action_open")
        self.action_close = QtWidgets.QAction(MainWindow)
        self.action_close.setObjectName("action_close")
        self.action_closeall = QtWidgets.QAction(MainWindow)
        self.action_closeall.setObjectName("action_closeall")
        self.action_pageconf = QtWidgets.QAction(MainWindow)
        self.action_pageconf.setObjectName("action_pageconf")
        self.action_printwindow = QtWidgets.QAction(MainWindow)
        self.action_printwindow.setObjectName("action_printwindow")
        self.action_exit = QtWidgets.QAction(MainWindow)
        self.action_exit.setObjectName("action_exit")
        self.action_cut = QtWidgets.QAction(MainWindow)
        self.action_cut.setObjectName("action_cut")
        self.action_copy = QtWidgets.QAction(MainWindow)
        self.action_copy.setObjectName("action_copy")
        self.action_paste = QtWidgets.QAction(MainWindow)
        self.action_paste.setObjectName("action_paste")
        self.action_delete = QtWidgets.QAction(MainWindow)
        self.action_delete.setObjectName("action_delete")
        self.action_init = QtWidgets.QAction(MainWindow)
        self.action_init.setObjectName("action_init")
        self.action_run_opeartion = QtWidgets.QAction(MainWindow)
        self.action_run_opeartion.setObjectName("action_run_opeartion")
        self.action_stop_opeartion = QtWidgets.QAction(MainWindow)
        self.action_stop_opeartion.setObjectName("action_stop_opeartion")
        self.action_finish_print = QtWidgets.QAction(MainWindow)
        self.action_finish_print.setObjectName("action_finish_print")
        self.action_finish_recode = QtWidgets.QAction(MainWindow)
        self.action_finish_recode.setObjectName("action_finish_recode")
        self.action_data_recode = QtWidgets.QAction(MainWindow)
        self.action_data_recode.setObjectName("action_data_recode")
        self.action_remotate = QtWidgets.QAction(MainWindow)
        self.action_remotate.setObjectName("action_remotate")
        self.action_window_max = QtWidgets.QAction(MainWindow)
        self.action_window_max.setObjectName("action_window_max")
        self.action_help = QtWidgets.QAction(MainWindow)
        self.action_help.setObjectName("action_help")
        self.action_patent = QtWidgets.QAction(MainWindow)
        self.action_patent.setObjectName("action_patent")
        self.action_about = QtWidgets.QAction(MainWindow)
        self.action_about.setObjectName("action_about")
        self.action_run = QtWidgets.QAction(MainWindow)
        self.action_run.setObjectName("action_run")
        self.action_rerun = QtWidgets.QAction(MainWindow)
        self.action_rerun.setObjectName("action_rerun")
        self.action_stop = QtWidgets.QAction(MainWindow)
        self.action_stop.setObjectName("action_stop")
        self.action_safe = QtWidgets.QAction(MainWindow)
        self.action_safe.setObjectName("action_safe")
        self.menu_file.addAction(self.action_open)
        self.menu_file.addAction(self.action_close)
        self.menu_file.addAction(self.action_closeall)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_pageconf)
        self.menu_file.addAction(self.action_printwindow)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_exit)
        self.menu_edit.addAction(self.action_cut)
        self.menu_edit.addAction(self.action_copy)
        self.menu_edit.addAction(self.action_paste)
        self.menu_edit.addAction(self.action_delete)
        self.menu_edit.addAction(self.action_init)
        self.menu_tool.addAction(self.action_safe)
        self.menu_operation.addAction(self.action_run_opeartion)
        self.menu_operation.addAction(self.action_stop_opeartion)
        self.menu_operation.addSeparator()
        self.menu_operation.addAction(self.action_finish_print)
        self.menu_operation.addAction(self.action_finish_recode)
        self.menu_operation.addAction(self.action_data_recode)
        self.menu_operation.addSeparator()
        self.menu_operation.addAction(self.action_remotate)
        self.menu_window.addAction(self.action_window_max)
        self.menu_help.addAction(self.action_help)
        self.menu_help.addAction(self.action_patent)
        self.menu_help.addAction(self.action_about)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_edit.menuAction())
        self.menubar.addAction(self.menu_operation.menuAction())
        self.menubar.addAction(self.menu_tool.menuAction())
        self.menubar.addAction(self.menu_window.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_run)
        self.toolBar.addAction(self.action_rerun)
        self.toolBar.addAction(self.action_stop)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "US_Cal_Test"))
        self.textBrowser_note.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600; color:#ff0000;\">US_Cal_Test_AnnexA_E4404B-2.0</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#550000;\">1、Set E4404B GPIB Address=18</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#550000;\">2、Set Constellation:QPSK/64QAM</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#550000;\">       NumFeq:(2:5.1MHz 35MHz   3:5.1MHz 35MHz 64.9MHz  4:5.1MHz 35MHz 64.9MHz 84.9MHz)  </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#550000;\">       NumPower(10:58, 52, 46, 40, 34, 28, 22, 16, 10, 8dBmV)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#550000;\">         (8:58, 52, 46, 40, 34, 28, 22, 16dBmV)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#550000;\">3、Test Result saved in: C:\\temp\\TestResult\\US_Cal_test.txt</span></p></body></html>"))
        self.label_savefile.setText(_translate("MainWindow", "SaveFile"))
        self.lineEdit_savefile.setPlaceholderText(_translate("MainWindow", "C:\\temp\\TestResults\\US_Cal_test.txt"))
        self.label_constellation.setText(_translate("MainWindow", "Constellation"))
        self.label_numfreq.setText(_translate("MainWindow", "NumFreq"))
        self.label_numpower.setText(_translate("MainWindow", "NumPower"))
        self.label_numpower_2.setText(_translate("MainWindow", "PowerIndex"))
        self.label_resource_name.setText(_translate("MainWindow", "Ports"))
        self.label_readstr.setText(_translate("MainWindow", "ReadedStr"))
        self.label_writestr.setText(_translate("MainWindow", "WriteSting"))
        self.label_Freqcurrent.setText(_translate("MainWindow", "Freq(MHz)"))
        self.label_normalCHP.setText(_translate("MainWindow", "NormalCHPower(dBmV)"))
        self.label_measureCHP.setText(_translate("MainWindow", "MeasureCHPower(dBmV)"))
        self.label_response.setText(_translate("MainWindow", "Response"))
        self.label_powerDiff.setText(_translate("MainWindow", "PowerDiff(dB)"))
        self.label_status.setText(_translate("MainWindow", "Status"))
        self.label_status_2.setText(_translate("MainWindow", "Stop/Start"))
        self.toolButton_choosepath.setText(_translate("MainWindow", "..."))
        self.menu_file.setTitle(_translate("MainWindow", "文件"))
        self.menu_edit.setTitle(_translate("MainWindow", "编辑"))
        self.menu_tool.setTitle(_translate("MainWindow", "工具"))
        self.menu_operation.setTitle(_translate("MainWindow", "操作"))
        self.menu_window.setTitle(_translate("MainWindow", "窗口"))
        self.menu_help.setTitle(_translate("MainWindow", "帮助"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_open.setText(_translate("MainWindow", "打开"))
        self.action_close.setText(_translate("MainWindow", "关闭"))
        self.action_closeall.setText(_translate("MainWindow", "全部关闭"))
        self.action_pageconf.setText(_translate("MainWindow", "页面设置"))
        self.action_printwindow.setText(_translate("MainWindow", "打印窗口"))
        self.action_exit.setText(_translate("MainWindow", "退出"))
        self.action_cut.setText(_translate("MainWindow", "剪切"))
        self.action_copy.setText(_translate("MainWindow", "复制"))
        self.action_paste.setText(_translate("MainWindow", "粘贴"))
        self.action_delete.setText(_translate("MainWindow", "删除"))
        self.action_init.setText(_translate("MainWindow", "重新初始化为默认值"))
        self.action_run_opeartion.setText(_translate("MainWindow", "运行"))
        self.action_stop_opeartion.setText(_translate("MainWindow", "停止"))
        self.action_finish_print.setText(_translate("MainWindow", "结束打印"))
        self.action_finish_recode.setText(_translate("MainWindow", "结束时记录"))
        self.action_data_recode.setText(_translate("MainWindow", "数据记录"))
        self.action_remotate.setText(_translate("MainWindow", "连接远程前面板"))
        self.action_window_max.setText(_translate("MainWindow", "最大化窗口"))
        self.action_help.setText(_translate("MainWindow", "显示及时帮助"))
        self.action_patent.setText(_translate("MainWindow", "专利信息"))
        self.action_about.setText(_translate("MainWindow", "关于"))
        self.action_run.setText(_translate("MainWindow", "运行"))
        self.action_run.setToolTip(_translate("MainWindow", "<html><head/><body><p>运行</p></body></html>"))
        self.action_rerun.setText(_translate("MainWindow", "继续运行"))
        self.action_rerun.setToolTip(_translate("MainWindow", "继续运行"))
        self.action_stop.setText(_translate("MainWindow", "中止执行"))
        self.action_stop.setToolTip(_translate("MainWindow", "中止执行"))
        self.action_safe.setText(_translate("MainWindow", "安全"))
